### PR TITLE
Fix failing unit tests

### LINKED ISSUE #9: Most unit tests are failing
Running `rspec` similarly to described in the [readme](https://github.com/Australian-Genomics/CTRL/blob/a7d34562d5290a041694bad45ae63abe1718cda9/README.md#-testing) fails:

```
% docker-compose run web bash -c 'RAILS_ENV=test bundle exec rspec'
[+] Running 1/0
 ⠿ Container ctrl-database-1  Running                                                                                                                                                                                      0.0s
Your RubyGems version (3.0.3) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`

An error occurred while loading ./spec/models/survey_config_spec.rb.
Failure/Error: require 'rails_helper'

LoadError:
  cannot load such file -- rails_helper
# ./spec/models/survey_config_spec.rb:1:in `<top (required)>'

Randomized with seed 35524


Finished in 0.18295 seconds (files took 8.36 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Randomized with seed 35524
```

To run the test suite, the file mentioned in the output (`spec/models/survey_config_spec.rb`) can be deleted because it only contains boilerplate code and no tests. Doing so really does allow the test suite to run, but 50 of the 98 tests fail:

```
Finished in 1.76 seconds (files took 8.45 seconds to load)
98 examples, 50 failures

Failed examples:

rspec ./spec/models/consent_step_spec.rb:8 # ConsentStep should be valid
rspec ./spec/services/answer_question_spec.rb:42 # AnswerQuestion#call there is an existing answer from the user updates the existing answer
rspec ./spec/services/answer_question_spec.rb:14 # AnswerQuestion#call answer doesn't exist saves the answer
rspec ./spec/services/answer_question_spec.rb:63 # AnswerQuestion#call consent question does not exist raises an error
rspec ./spec/models/step_review_spec.rb:8 # StepReview 
rspec ./spec/models/step_review_spec.rb:12 # StepReview associations 
rspec ./spec/models/step_review_spec.rb:11 # StepReview associations 
rspec ./spec/models/step_review_spec.rb:19 # StepReview validations 
rspec ./spec/models/step_review_spec.rb:17 # StepReview validations 
rspec ./spec/models/step_review_spec.rb:16 # StepReview validations 
rspec ./spec/models/user_spec.rb:7 # User 
rspec ./spec/models/user_spec.rb:8 # User 
rspec ./spec/models/user_spec.rb:9 # User 
rspec ./spec/models/user_spec.rb:6 # User 
rspec ./spec/models/user_spec.rb:156 # User#reset_password should skip validations on update of some fields
rspec ./spec/models/user_spec.rb:37 # User validate study_id when third number is not between 2 to 4 after capital A 
rspec ./spec/models/user_spec.rb:36 # User validate study_id when third number is not between 2 to 4 after capital A 
rspec ./spec/models/user_spec.rb:35 # User validate study_id when third number is not between 2 to 4 after capital A 
rspec ./spec/models/user_spec.rb:21 # User validate study_id when study id not started with capital A 
rspec ./spec/models/user_spec.rb:19 # User validate study_id when study id not started with capital A 
rspec ./spec/models/user_spec.rb:20 # User validate study_id when study id not started with capital A 
rspec ./spec/models/user_spec.rb:43 # User validate study_id when length of numbers after capital A is less than 7 
rspec ./spec/models/user_spec.rb:44 # User validate study_id when length of numbers after capital A is less than 7 
rspec ./spec/models/user_spec.rb:45 # User validate study_id when length of numbers after capital A is less than 7 
rspec ./spec/models/user_spec.rb:28 # User validate study_id when first number is not between 0 to 4 after capital A 
rspec ./spec/models/user_spec.rb:27 # User validate study_id when first number is not between 0 to 4 after capital A 
rspec ./spec/models/user_spec.rb:29 # User validate study_id when first number is not between 0 to 4 after capital A 
rspec ./spec/models/user_spec.rb:60 # User validate study_id when user have a valid Study id 
rspec ./spec/models/user_spec.rb:59 # User validate study_id when user have a valid Study id 
rspec ./spec/models/user_spec.rb:51 # User validate study_id when length of numbers after capital A is greater than 7 
rspec ./spec/models/user_spec.rb:52 # User validate study_id when length of numbers after capital A is greater than 7 
rspec ./spec/models/user_spec.rb:53 # User validate study_id when length of numbers after capital A is greater than 7 
rspec ./spec/models/user_spec.rb:85 # User validations should have a mandatory first name
rspec ./spec/models/user_spec.rb:95 # User validations should have a strong password
rspec ./spec/models/user_spec.rb:90 # User validations should have a mandatory last name
rspec ./spec/models/user_spec.rb:80 # User validations should have a study id
rspec ./spec/models/user_spec.rb:100 # User validations should have kin details when is parent is set to false
rspec ./spec/models/user_spec.rb:106 # User validations should have child details when is parent is set to true
rspec ./spec/models/user_spec.rb:65 # User validations should have a mandatory preferred contact method
rspec ./spec/models/user_spec.rb:75 # User validations should have a mandatory dob
rspec ./spec/models/user_spec.rb:70 # User validations should have a mandatory flasghip
rspec ./spec/models/user_spec.rb:115 # User validations Date of birth validations when it is user dob when user enters date of birth in future returns error cannot enter the date from the future
rspec ./spec/models/user_spec.rb:124 # User validations Date of birth validations when it is user dob when user enters date of birth in a wrong format returns error invalid format
rspec ./spec/models/user_spec.rb:144 # User validations Date of birth validations when it is user child_dob when user enters date of birth in a wrong format returns error invalid format
rspec ./spec/models/user_spec.rb:135 # User validations Date of birth validations when it is user child_dob when user enters date of birth in future returns error cannot enter the date from the future
rspec ./spec/models/question_answer_spec.rb:8 # QuestionAnswer 
rspec ./spec/models/question_answer_spec.rb:16 # QuestionAnswer validations 
rspec ./spec/models/question_answer_spec.rb:18 # QuestionAnswer validations 
rspec ./spec/models/question_answer_spec.rb:11 # QuestionAnswer associations 
rspec ./spec/models/question_answer_spec.rb:12 # QuestionAnswer associations 

Randomized with seed 21677
```

### PR DESCRIPTION
**Pull request by DoxasticFox**
Resolves #9

### CODE REVIEW

File: spec/models/study_code_spec.rb [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+    end
+
+    context 'when StudyCode has a valid Study id' do
+      let(:study_code) { StudyCode.create(title: 'A1543457') }
+
+      it { expect(study_code).to be_a(StudyCode) }
+      it { expect(study_code.errors[:title]).to eq([]) }
+    end
+  end
+end
```
Comment (DoxasticFox) [inline spec/models/study_code_spec.rb:52]: This was copied from `spec/models/user_spec.rb` with trivial modifications (e.g. to variable names).

File: spec/factories/consent_step.rb [hunk 2]
```diff
@@ -1,6 +1,6 @@
 FactoryBot.define do
   factory :consent_step do
-    sequence(:order) { |n| n }
+    sequence(:order) { |n| n + 1 }
```
Comment (DoxasticFox) [inline spec/factories/consent_step.rb:3]: Some tests were failing because the `order==1st` step requires a non-empty `tour_video` field. This numbers the order fields starting at 2.

**Review by mathob — APPROVED** [review]
Using docker I can now run the bundle exec rspec command without error
